apiVersion: v1
kind: Service
metadata:
  name: service-node-file-app
spec:
  selector:
    app: node-file-app
  ports:
    - protocol: TCP
      port: 8082 # External access port
      targetPort: 3000 # Port the container listens on
  type: NodePort # Change this if using cloud provider (LoadBalancer for AWS/GCP)
